# Generated by Django 3.2.5 on 2021-12-04 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enterdata', '0004_rename_birder_sighting_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('name', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('slug', models.SlugField(unique=True)),
            ],
        ),
    ]
