# Generated by Django 3.2.5 on 2021-12-04 21:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('enterdata', '0005_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='species',
            name='category',
            field=models.ForeignKey(default='bird', on_delete=django.db.models.deletion.PROTECT, to='enterdata.category'),
            preserve_default=False,
        ),
    ]
